main: xyz.zip8919.mcplugin.EventsCountdown.EventsCountdown
version: 1.0.0-SNAPSHOT
name: EventsCountdown
author: zip8919
api-version: 1.13
soft-depend: [PlaceholderAPI,LiteMotto]

commands:
  examcountdown:
    description: 控制高考倒计时显示
    usage: /<command> [on|off|toggle|help|reload]
    aliases: [ec]

permissions:
  examcountdown.admin:
    description: 允许使用管理员命令
    default: op