main: xyz.zip8919.mcplugin.EventsCountdown.EventsCountdown
version: 1.3.0
name: EventsCountdown
author: zip8919 & baicaizhale
api-version: 1.13
soft-depend: [PlaceholderAPI,LiteMotto]

commands:
  eventscountdown:
    description: 控制事件倒计时显示
    usage: /<command> [on|off|toggle|help|reload]
    aliases: [ec]

permissions:
  eventscountdown.admin:
    description: 允许使用管理员命令
    default: op